### ISSUE TITLE
 Issue with Service Worker Registration in Web App

### ISSUE THREAD

**Issue by daud99** [JRaviLab/molevolvr2.0#16]
I'm an Outreachy applicant exploring the MolEvolvR package. I successfully ran the MolEvolvR package, and then I thought of checking its web app as well. I cloned the repository and followed the instructions, but I encountered the following error when I opened the web app in my browser:

`
getWorkerInstance.ts:85  Uncaught (in promise) Error: [MSW] Failed to register the Service Worker:

Failed to register a ServiceWorker for scope ('http://localhost:5713/') with script ('http://localhost:5713/mockServiceWorker.js'): The script has an unsupported MIME type ('text/html').
    at getWorkerInstance (getWorkerInstance.ts:85:11)
    at async startWorkerInstance (createStartHandler.ts:29:24)
    at async SetupWorkerApi.start (setupWorker.ts:179:12)
    at async main.tsx:14:5
    `
    
I looked into the code and found that the mockServiceWorker.js file is included in the .gitignore file, so it's not part of the repository. After generating it, I was able to run the application successfully in the browser.

I have a couple of questions:

Shouldn't the mockServiceWorker.js file be included in the repository from the start, and why isn't it there?
Do we need to rerun the Docker command (./run_stack.sh) every time we make a change to the code? Can't we have something like hot reloading for the frontend?
I'm not sure if this is deliberate or if it's an issue, but if it is, I would be happy to help resolve it.

Thank you!

@jananiravi @vincerubinetti

**Comment by vincerubinetti** [comment]
This is correct, good catch. The script is supposed to be committed into the repository.

Feel free to submit a PR to fix.

**Comment by daud99** [comment]
@vincerubinetti Okay I'm on it. 

Thanks
