### ISSUE TITLE
Limit pan in network visualization

### ISSUE THREAD

**Issue by vincerubinetti** [JRaviLab/molevolvr2.0#18]
There is a limit to how far you can zoom in/out in the network component, but no limits for how far you can drag the view away from the content.

Add pan limits such that the user can't drag the view too far away from nodes/edges. This is not a built in feature in Cytoscape.js, the library we're using for the visualization:

https://github.com/cytoscape/cytoscape.js/issues/1329

This will likely involve listening for the [`viewport` event](https://js.cytoscape.org/#events/graph-events) and limiting the pan accordingly.

Reference:
https://stackoverflow.com/questions/55057075/how-to-check-if-my-cytoscape-js-graph-is-out-of-view-even-partially-after-pann

**Comment by daud99** [comment]
@vincerubinetti can you assign this one to me?

**Comment by daud99** [comment]
This one looks exciting!

**Comment by daud99** [comment]
@vincerubinetti
