### ISSUE TITLE
Add fit button to network visualization

### ISSUE THREAD

**Issue by vincerubinetti** [JRaviLab/molevolvr2.0#19]
Currently, you can double click the network visualization to fit the view to contents. But not everyone will know to do that. Let's add a "fit" button with these buttons:

<img width="169" alt="Screenshot 2024-10-03 at 12 10 56 PM" src="https://github.com/user-attachments/assets/53475e8e-e0ca-4608-b91d-ce3f81c19523">

Will need to find an appropriate icon that is distinct from the "fullscreen" button. The tooltip for the button should be something like "Fit view to contents (or double-click viz)".

**Comment by kemsguy7** [comment]
Kindly assign this to me

**Comment by kemsguy7** [comment]
@vincerubinetti , please kindly review
<img width="259" alt="Screenshot 2024-10-09 at 20 17 36" src="https://github.com/user-attachments/assets/467bf050-9994-4e14-ad2c-0391e5f4761a">
