### ISSUE TITLE
Fill in some About page text

### ISSUE THREAD

**Issue by vincerubinetti** [JRaviLab/molevolvr2.0#21]
The 1.0 version of MolEvolvR has a [help page](https://jravilab.cuanschutz.edu/molevolvr/?r=liasix&p=help) with three tabs and a lot of static content.

Much of this, if not most, is very specific to the design of 1.0, and will thus not be applicable to 2.0. Avoid transferring things that are very layout-specific -- e.g. "go to Advanced Options > Maximum Hits" -- as these may move around or be renamed in 2.0. But there are more general things -- like compatibility, team, links, contact, funding, case studies -- that we can start adding to the 2.0 About page.

**Comment by daud99** [comment]
I can take up this one as well. @vincerubinetti 
Thanks

**Comment by Sproff** [comment]
Interested in this, kindly assign to me @vincerubinetti
