### ISSUE TITLE
Implement color contrast accessibility test

### ISSUE THREAD

**Issue by vincerubinetti** [JRaviLab/molevolvr2.0#22]
`accessibility.spec.ts` currently has the following:

```
/** NOT WORKING YET https://github.com/StackExchange/apca-check/issues/143 */
registerAPCACheck("bronze");

// ...

      const { violations } = await new AxeBuilder({ page })
        /** https://github.com/dequelabs/axe-core/issues/3325 */
        .options({ rules: { "color-contrast": { enabled: false } } })
        .analyze();
```

See the two github issues linked there for full details. In summary:

We have disabled the standard "color-contrast" accessibility test, because it is frankly not very accurate or good. I want to replace it with the newer and better [advanced perceptual contrast algorithm](https://www.google.com/search?q=apca+%28advanced+perceptual+contrast+algorithm), but I'm having trouble integrating that `StackExchange/apca-check` library with Playwright.

This seems to be challenging to fix; see the first issue for problems I've encountered and what I've tried.

**Comment by vincerubinetti** [comment]
To ensure the test is actually running and catching errors, you could for example change the light-mode `--black` theme variable to `#ffffff`, which would definitely be a contrast violation:

<img width="500" alt="Screenshot 2024-10-03 at 12 52 10 PM" src="https://github.com/user-attachments/assets/cd5e7bc3-6963-43ce-a18b-cb3d53405beb">

**Comment by valentina-buoro** [comment]
hi @vincerubinetti can I work on this?

**Comment by vincerubinetti** [comment]
@valentina-buoro Please abandon work on this. I've deemed this infeasible/impossible. See the discussion here:

https://github.com/StackExchange/apca-check/issues/143

**Comment by valentina-buoro** [comment]
okay @vincerubinetti . Lighthouse seems like a good tool to test accessibility. Although doing it manually might be tedious.

**Comment by vincerubinetti** [comment]
See this issue I created: https://github.com/JRaviLab/molevolvr2.0/issues/33
